# Generated by Django 2.0.6 on 2018-06-11 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='应用名')),
                ('description', models.CharField(max_length=150, verbose_name='描述')),
                ('icon', models.ImageField(null=True, upload_to='', verbose_name='图标')),
                ('type', models.IntegerField(choices=[(1, '目录'), (2, '报表数据源')], verbose_name='类型')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('enable', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
        ),
    ]
