# Generated by Django 2.0.6 on 2018-06-11 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_key', models.BooleanField(default=False, verbose_name='唯一标示')),
                ('name', models.CharField(max_length=1000, verbose_name='字段名')),
                ('bind_key', models.CharField(max_length=20, verbose_name='绑定标示')),
                ('type', models.IntegerField(choices=[(1, '文本'), (2, '日期'), (2, '日期时间'), (2, '整数'), (2, '浮点数'), (2, '货币')], verbose_name='字段类型')),
                ('order_index', models.IntegerField(verbose_name='排序编号')),
                ('default_show', models.BooleanField(default=True, verbose_name='字段类型')),
                ('enable', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='parent_id',
            field=models.IntegerField(null=True, verbose_name='父节点'),
        ),
        migrations.AddField(
            model_name='field',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.App'),
        ),
    ]
