# Generated by Django 2.0.6 on 2018-06-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0002_auto_20180611_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.CharField(blank=True, max_length=150, verbose_name='描述'),
        ),
    ]
