# Generated by Django 2.0.6 on 2018-06-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0003_auto_20180612_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='icon_content',
            field=models.BinaryField(null=True, verbose_name='文件内容'),
        ),
        migrations.AddField(
            model_name='app',
            name='icon_ext_name',
            field=models.CharField(blank=True, max_length=10, verbose_name='文件后缀'),
        ),
        migrations.AddField(
            model_name='app',
            name='icon_file_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='图标'),
        ),
    ]
