# Generated by Django 2.0.5 on 2018-06-30 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0005_auto_20180621_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apprecord',
            name='last_update_user',
        ),
        migrations.RemoveField(
            model_name='apprecorditem',
            name='record_id',
        ),
        migrations.AddField(
            model_name='apprecorditem',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analyse.AppRecord'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apprecord',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.App'),
        ),
        migrations.AlterField(
            model_name='apprecord',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
